### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by bratanac24**
Finished desktop, tablet and mobile view.

### CODE REVIEW

**Comment by ghost** [comment]
Pay attention to the mobile resolution(image section).

**Comment by bratanac24** [comment]
> Pay attention to the mobile resolution(image section).

im working on it, hoping to finish by tomorrow

**Comment by ghost** [comment]
image
This section is not in the center. Please correct that.

**Comment by bratanac24** [comment]
Could you check again, because on my computer it works in Chrome, Mozila and Safari.
And also could you tell me which browser are you using?

**Comment by ghost** [comment]
Sorry, now I see you wrote. I'm using Chrome, Linux.

**Pull request merged**
